### PR TITLE
Update github-toggle-expanders.user.js

### PR DESCRIPTION
**Pull request by darkred**
A minor addition in order to work in releases pages too, e.g. https://github.com/ahkscript/SublimeAutoHotkey/releases.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @darkred!

Thanks!! 😸

**Comment by darkred** [comment]
BTW, I'd like to ask you this, please:
since you had invited me a collaborator to this repo,
whenever have a suggested addition for a script of yours (like this one),
would you prefer if I immediately pressed the "Merge" button myself (provided that I have included a script's version bump, of course),
or it's better to only make a pull request and let you decide whether to merge?

**Comment by Mottie** [comment]
Yeah, I'm fine with you pushing to the master branch. I'll add a contributions file soon to spell out what I've been doing for each release. Thanks again!

**Comment by darkred** [comment]
Great! I'm glad.

**Comment by Mottie** [comment]
Done - [CONTRIBUTING.md](https://github.com/Mottie/GitHub-userscripts/blob/master/CONTRIBUTING.md).

**Pull request merged**
