### PR TITLE
Sort-content: Add support for gist.github.com

### PR DESCRIPTION
**Pull request by AviSynthPlus**

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @AviSynthPlus!

Can you please provide an example page. What needs to be sorted?

**Comment by AviSynthPlus** [comment]
https://gist.github.com/AviSynthPlus/6c1ede233c0b068270e2d0d2af550de6

**Comment by Mottie** [comment]
Cool... I'll update the css to make the sorting arrows show up.

**Comment by AviSynthPlus** [comment]
Thank you.

**Pull request merged**
