### PR TITLE
fix 

### PR DESCRIPTION
**Pull request by Democookie**
1. Fix the bowser warnings about dangerous & deceptive content
2. fix the open link display when html's name is too long,it wiil be hidden.

### CODE REVIEW

**Comment by Mottie** [comment]
Thanks!!

**Comment by Mottie** [comment]
I commited a change to prepend the preview link to the file name since I didn't like the links on the separate lines. I hope it isn't too far off from what you are trying to do. Thanks again!

**Comment by Democookie** [comment]
> I commited a change to prepend the preview link to the file name since I didn't like the links on the separate lines. I hope it isn't too far off from what you are trying to do. Thanks again!

yeah , i just found the Problem .I agree to your solution,it it great!!

**Comment by Democookie** [comment]
> I commited a change to prepend the preview link to the file name since I didn't like the links on the separate lines. I hope it isn't too far off from what you are trying to do. Thanks again!

yeah , i just found the Problem .I agree to your solution,it is great and better!!

**Comment by Democookie** [comment]
> I commited a change to prepend the preview link to the file name since I didn't like the links on the separate lines. I hope it isn't too far off from what you are trying to do. Thanks again!

yeah , i just found the problem .I agree to your solution,it is great and better!!

**Comment by Democookie** [comment]
> I commited a change to prepend the preview link to the file name since I didn't like the links on the separate lines. I hope it isn't too far off from what you are trying to do. Thanks again!

May the links display 14px better? 12px seems small ?

**Comment by Mottie** [comment]
> May the links display 14px better? 12px seems small ?

Done.

**Pull request merged**
