### PR TITLE
Github Code Colors - Fix GitHub domains include

### PR DESCRIPTION
**Pull request by meequrox**
There was a rule that only included GitHub subdomains:
`// @include     https://*.github.com/*`

Due this, the script only worked with gists. This PR includes the `github.com` domain (as in other scripts) and fixes this issue.

### CODE REVIEW

**Review by Technetium1 — APPROVED** [review]
Looks fine.

**Comment by meequrox** [comment]
Just a reminder

**Comment by Mottie** [comment]
All of the [`@include` rules need to be updated to use `@match`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/blob/main/docs/rules/better-use-match.md), so please update this PR and I'll merge it.

**Comment by meequrox** [comment]
> All of the [`@include` rules need to be updated to use `@match`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/blob/main/docs/rules/better-use-match.md), so please update this PR and I'll merge it.

Done

**Pull request merged**
